version: '3.3'

services:
  alist:
    image: wikihostinc/looking-glass-server:latest
    restart: always
    container_name: als
    logging:
        driver: "json-file"
        options:
            max-size: "1m"
    ports:
      - "8401:80/tcp"
      - "8402:8402/tcp"
    environment:
      - TZ=Asia/Shanghai
      - UTILITIES_IPERF3_PORT_MAX=8402
      - UTILITIES_IPERF3_PORT_MIN=8402
    # network_mode: host

