services:
  alist:
    image: xhofe/alist:${IMAGE_TAG:-latest}
    restart: always
    container_name: alist
    logging:
        driver: "json-file"
        options:
            max-size: "1m"
    volumes:
      - alist_data:/opt/alist/data
    ports:
      - "5244:5244/tcp"
    # network_mode: host
    
volumes:
  alist_data:
