services:
  ddns-go:
    image: jeessy/ddns-go:${IMAGE_TAG:-latest}
    restart: always
    container_name: ddns-go
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ddnsgo_data:/root/
    #监听地址9877 监听秒数600
    command: -l :9876 -f 600
    # ports:
    #   - "9876:9877"
    network_mode: "host"


volumes:
  ddnsgo_data:
