services:
    prometheus:
        command:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --web.console.templates=/etc/prometheus/consoles
            - --storage.tsdb.retention.time=200h
            - --web.enable-admin-api
        container_name: prometheus
        image: prom/prometheus:v3.2.1
        labels:
            createdBy: Apps
        ports:
            - 9090:9090
        restart: always
        volumes:
            - prometheus:/etc/prometheus/
            - prometheus:/prometheus
        environment:
            - TZ=Asia/Shanghai
    grafana:
        container_name: grafana
        image: grafana/grafana:11.5.2
        ports:
            - 9091:3000
        restart: always
        user: "0"
        volumes:
            - grafana:/var/lib/grafana
        environment:
            - TZ=Asia/Shanghai
            
volumes:
    prometheus:
    grafana:
