services:
    prometheus:
        command:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --web.console.templates=/etc/prometheus/consoles
            - --storage.tsdb.retention.time=200h
            - --web.enable-admin-api
        container_name: prometheus
        image: prom/prometheus:v3.2.1
        labels:
            createdBy: Apps
        ports:
            - 9090:9090
        restart: unless-stopped
        volumes:
            - prometheus:/etc/prometheus/
            - prometheus:/prometheus
            # - /etc/localtime:/etc/localtime:ro
            # - /etc/timezone:/etc/timezone:ro
        environment:
            - TZ=Asia/Shanghai
        extra_hosts:
            - "local-server:host-gateway" # 这里改成了 local-server 
            # sudo ufw allow from 172.17.0.0/16 to any port 9100           
    grafana:
        container_name: grafana
        image: grafana/grafana-oss
        ports:
            - 9091:3000
        restart: unless-stopped
        user: "0"
        volumes:
            - grafana:/var/lib/grafana
        environment:
            - TZ=Asia/Shanghai

volumes:
    prometheus:
    grafana:
