services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:${IMAGE_TAG:-latest}
    container_name: 3x-ui
    restart: unless-stopped
    network_mode: host
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
    volumes:
      - 3x_ui_data:/etc/x-ui
      - 3x_ui_data:/root/cert

volumes:
  3x_ui_data: