version: '3.3'

services:
  x-ui:
    image: enwaiax/x-ui:alpha-zh
    restart: always
    container_name: x-ui-new
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./workdir/db:/etc/x-ui"
      - "./workdir/cert:/root/cert"
    logging:
        driver: "json-file"
        options:
            max-size: "1m"
    network_mode: host
