services:
  renewx:
    image: harryczqp/renewx
    restart: always
    container_name: renewx
    volumes:
      - "rustdesk_data/deploy:/app/RenewX/Deploy"
      - "rustdesk_data/appdata:/app/RenewX/appdata"
    ports:
      - "1066:1066/tcp"

volumes:
  rustdesk_data: