services:
  renewx:
    image: harryczqp/renewx
    restart: unless-stopped
    container_name: renewx
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "data:/app/RenewX/Deploy"
      - "data:/app/RenewX/appdata"
    ports:
      - "1066:1066/tcp"
    network_mode: bridge

volumes:
  data: