services:
  renewx:
    image: harryczqp/renewx
    restart: always
    container_name: renewx
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "renewx_data:/app/RenewX/Deploy"
      - "renewx_data:/app/RenewX/appdata"
    ports:
      - "1066:1066/tcp"

volumes:
  renewx_data: