services:
  aiclient-api:
    # 方式一：使用 Docker Hub 预构建镜像（默认，推荐）
    # 使用方法: docker compose up -d
    image: justlikemaki/aiclient-2-api:latest
    container_name: aiclient2api
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "3001:3000"
      #Gemini: 8085, Antigravity: 8086, iFlow: 8087, Codex: 1455, Kiro: 19876-19880
      - "8085-8087:8085-8087" 
      - "1455:1455"
      - "19876-19880:19876-19880"
    volumes:
      - data:/app/configs
    environment:
      - ARGS=
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    logging:
        driver: "json-file"
        options:
            max-size: "1m"   
volumes:
  data:
