---
services:
  s-ui:
    image: alireza7/s-ui
    container_name: s-ui
    environment:
      - TZ=Asia/Shanghai
    hostname: "s-ui"
    volumes:
      - "data:/app/db"
      - "data:/app/cert"
    tty: true
    restart: unless-stopped
    network_mode: host
    # ports:
    #   - "2095:2095"
    #   - "2096:2096"
    # network_mode: bridge
    entrypoint: "./entrypoint.sh"
    logging:
        driver: "json-file"
        options:
            max-size: "1m"

volumes:
  data: