services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    environment:
      - TZ=Asia/Shanghai
    command: hbbs
    volumes:
      - ./data:/root
    network_mode: "host"

    restart: unless-stopped
