services:
  adguard:
    image: adguard/adguardhome:${IMAGE_TAG:-latest}
    restart: always
    container_name: adguard
    volumes:
      - data:/opt/adguardhome/work
      - data:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3001:3000/tcp"
    # network_mode: host
    network_mode: bridge
volumes:
  data: