#!/usr/bin/env sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
SOURCE_SCRIPT="$SCRIPT_DIR/sync_ssl_to_esa.sh"

DEFAULT_INSTALL_PATH="/root/sync_ssl.sh"
DEFAULT_CONFIG_FILE="/etc/sync-ssl-to-esa.env"
DEFAULT_SOURCE_BASE_URL="http://192.168.112.1:16602/"
DEFAULT_SOURCE_USER="admin"
DEFAULT_SOURCE_PASS="admin"
DEFAULT_SOURCE_CERT_FILE="ggit.cc.pem"
DEFAULT_SOURCE_KEY_FILE="ggit.cc.key"
DEFAULT_SSL_DIR="/etc/configs/nginx/ssl"
DEFAULT_ESA_SITE_ID="1098350467844576"
DEFAULT_ESA_CERT_NAME="ggit.cc"
DEFAULT_ESA_ENDPOINT="esa.cn-hangzhou.aliyuncs.com"
DEFAULT_ESA_VERSION="2024-09-10"
DEFAULT_CRON_SCHEDULE="1 0,8 * * *"
DEFAULT_LOG_DIR="/var/log/sync-ssl"
CRON_MARKER="# sync-ssl-to-esa"

log() {
  printf '%s\n' "$*"
}

die() {
  log "ERROR: $*" >&2
  exit 1
}

need_source_script() {
  [ -f "$SOURCE_SCRIPT" ] || die "missing source script: $SOURCE_SCRIPT"
}

prompt() {
  prompt_text=$1
  default_value=$2

  if [ -n "$default_value" ]; then
    printf '%s [%s]: ' "$prompt_text" "$default_value" >&2
  else
    printf '%s: ' "$prompt_text" >&2
  fi

  IFS= read -r answer || answer=
  if [ -n "$answer" ]; then
    printf '%s\n' "$answer"
  else
    printf '%s\n' "$default_value"
  fi
}

prompt_yes_no() {
  prompt_text=$1
  default_value=$2

  while :; do
    if [ "$default_value" = "y" ]; then
      suffix="Y/n"
    else
      suffix="y/N"
    fi

    printf '%s [%s]: ' "$prompt_text" "$suffix" >&2
    IFS= read -r answer || answer=
    answer=${answer:-$default_value}

    case "$answer" in
      y|Y|yes|YES|Yes)
        return 0
        ;;
      n|N|no|NO|No)
        return 1
        ;;
      *)
        log "Please answer y or n."
        ;;
    esac
  done
}

shell_quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

write_env_line() {
  env_key=$1
  env_value=$2
  printf '%s=%s\n' "$env_key" "$(shell_quote "$env_value")" >> "$CONFIG_FILE"
}

install_script() {
  install_dir=$(dirname "$INSTALL_PATH")
  mkdir -p "$install_dir"
  cp "$SOURCE_SCRIPT" "$INSTALL_PATH"
  chmod 755 "$INSTALL_PATH"
}

write_config() {
  config_dir=$(dirname "$CONFIG_FILE")
  mkdir -p "$config_dir"

  old_umask=$(umask)
  umask 077
  : > "$CONFIG_FILE"
  umask "$old_umask"

  {
    printf '# Generated by sync-ssl-to-esa install.sh\n'
    printf '# Edit this file, then run %s\n' "$INSTALL_PATH"
  } >> "$CONFIG_FILE"

  write_env_line SOURCE_BASE_URL "$SOURCE_BASE_URL"
  write_env_line SOURCE_USER "$SOURCE_USER"
  write_env_line SOURCE_PASS "$SOURCE_PASS"
  write_env_line SOURCE_CERT_FILE "$SOURCE_CERT_FILE"
  write_env_line SOURCE_KEY_FILE "$SOURCE_KEY_FILE"
  write_env_line SSL_DIR "$SSL_DIR"
  write_env_line ESA_PUSH "$ESA_PUSH"
  write_env_line ALIYUN_ESA_SITE_ID "$ALIYUN_ESA_SITE_ID"
  write_env_line ALIYUN_ESA_CERT_NAME "$ALIYUN_ESA_CERT_NAME"
  write_env_line ALIYUN_ESA_ENDPOINT "$ALIYUN_ESA_ENDPOINT"
  write_env_line ALIYUN_ESA_VERSION "$ALIYUN_ESA_VERSION"
  write_env_line ALIYUN_PROFILE "$ALIYUN_PROFILE"
  write_env_line NGINX_RELOAD_CMD "$NGINX_RELOAD_CMD"

  chmod 600 "$CONFIG_FILE" 2>/dev/null || true
}

install_cron() {
  mkdir -p "$LOG_DIR"

  cron_tmp=$(mktemp)
  cron_new=$(mktemp)
  trap 'rm -f "$cron_tmp" "$cron_new"' EXIT INT TERM

  crontab -l > "$cron_tmp" 2>/dev/null || true
  grep -v "$CRON_MARKER" "$cron_tmp" > "$cron_new" || true
  printf '%s SYNC_SSL_CONFIG=%s %s >> %s/sync_ssl.log 2>&1 %s\n' \
    "$CRON_SCHEDULE" \
    "$(shell_quote "$CONFIG_FILE")" \
    "$(shell_quote "$INSTALL_PATH")" \
    "$LOG_DIR" \
    "$CRON_MARKER" >> "$cron_new"

  crontab "$cron_new"
}

check_tools() {
  command -v curl >/dev/null 2>&1 || log "WARN: curl not found. Please install curl before running the sync script."
  command -v openssl >/dev/null 2>&1 || log "WARN: openssl not found. Cert/key validation will be skipped."

  if [ "$ESA_PUSH" = "1" ] && ! command -v aliyun >/dev/null 2>&1; then
    log "WARN: aliyun CLI not found. ESA upload will fail until aliyun CLI is installed and configured."
  fi
}

main() {
  need_source_script

  log "sync-ssl-to-esa interactive installer"
  log ""

  INSTALL_PATH=$(prompt "Install script path" "$DEFAULT_INSTALL_PATH")
  CONFIG_FILE=$(prompt "Config file path" "$DEFAULT_CONFIG_FILE")

  log ""
  log "Source certificate server"
  SOURCE_BASE_URL=$(prompt "Source base URL" "$DEFAULT_SOURCE_BASE_URL")
  SOURCE_USER=$(prompt "Source username" "$DEFAULT_SOURCE_USER")
  SOURCE_PASS=$(prompt "Source password" "$DEFAULT_SOURCE_PASS")
  SOURCE_CERT_FILE=$(prompt "Source certificate filename" "$DEFAULT_SOURCE_CERT_FILE")
  SOURCE_KEY_FILE=$(prompt "Source private key filename" "$DEFAULT_SOURCE_KEY_FILE")
  SSL_DIR=$(prompt "Local SSL directory" "$DEFAULT_SSL_DIR")

  log ""
  if prompt_yes_no "Upload to Alibaba Cloud ESA after pulling" "y"; then
    ESA_PUSH=1
    ALIYUN_ESA_SITE_ID=$(prompt "ESA SiteId" "$DEFAULT_ESA_SITE_ID")
    ALIYUN_ESA_CERT_NAME=$(prompt "ESA certificate name" "$DEFAULT_ESA_CERT_NAME")
    ALIYUN_ESA_ENDPOINT=$(prompt "ESA endpoint" "$DEFAULT_ESA_ENDPOINT")
    ALIYUN_ESA_VERSION=$(prompt "ESA API version" "$DEFAULT_ESA_VERSION")
    ALIYUN_PROFILE=$(prompt "Aliyun CLI profile, empty means default" "")
  else
    ESA_PUSH=0
    ALIYUN_ESA_SITE_ID=""
    ALIYUN_ESA_CERT_NAME=""
    ALIYUN_ESA_ENDPOINT="$DEFAULT_ESA_ENDPOINT"
    ALIYUN_ESA_VERSION="$DEFAULT_ESA_VERSION"
    ALIYUN_PROFILE=""
  fi

  log ""
  NGINX_RELOAD_CMD=$(prompt "Nginx reload command, empty to skip" "")

  log ""
  if prompt_yes_no "Install cron job" "y"; then
    INSTALL_CRON=1
    CRON_SCHEDULE=$(prompt "Cron schedule" "$DEFAULT_CRON_SCHEDULE")
    LOG_DIR=$(prompt "Cron log directory" "$DEFAULT_LOG_DIR")
  else
    INSTALL_CRON=0
    CRON_SCHEDULE="$DEFAULT_CRON_SCHEDULE"
    LOG_DIR="$DEFAULT_LOG_DIR"
  fi

  log ""
  install_script
  write_config
  mkdir -p "$SSL_DIR"

  if [ "$INSTALL_CRON" = "1" ]; then
    install_cron
  fi

  check_tools

  log ""
  log "Installed:"
  log "  script: $INSTALL_PATH"
  log "  config: $CONFIG_FILE"
  if [ "$INSTALL_CRON" = "1" ]; then
    log "  cron: $CRON_SCHEDULE $INSTALL_PATH"
    log "  log: $LOG_DIR/sync_ssl.log"
  fi

  log ""
  log "Run once now:"
  log "  SYNC_SSL_CONFIG=$(shell_quote "$CONFIG_FILE") $(shell_quote "$INSTALL_PATH")"
}

main "$@"
