services:
  ddns-go:
    image: jeessy/ddns-go
    restart: always
    container_name: ddns-go
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./workdir/.ddns_go_config.yaml:/root/.ddns_go_config.yaml"
    #监听地址9877 监听秒数600
    command: -l :9877 -f 600
    logging:
        driver: "json-file"
        options:
            max-size: "1m"
    network_mode: host