version: '3'

services:
  sing-box:
    image: gzxhwq/sing-box:1.12.0-rc.3
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /etc/sing-box/:/etc/sing-box/
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - TZ=Asia/Shanghai
