services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    environment:
      - TZ=Asia/Shanghai
    command: hbbs
    volumes:
      - data:/root
    network_mode: "host"

    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    environment:
      - TZ=Asia/Shanghai
    command: hbbr
    volumes:
      - data:/root
    network_mode: "host"
    restart: unless-stopped

volumes:
  data:


# # 添加 TCP 端口范围 21115 到 21119
# sudo ufw allow 21115:21119/tcp comment 'RustDesk TCP Ports'

# # 添加 UDP 端口 21116
# sudo ufw allow 21116/udp comment 'RustDesk UDP Port'