services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    environment:
      - TZ=Asia/Shanghai
    command: hbbs
    volumes:
      - rustdesk_data:/root
    network_mode: "host"

    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    environment:
      - TZ=Asia/Shanghai
    command: hbbr
    volumes:
      - rustdesk_data:/root
    network_mode: "host"
    restart: unless-stopped

volumes:
  rustdesk_data: