version: '3.3'

services:
  bitwarden:
    image: bitwarden/server
    restart: always
    container_name: bitwarden
    environment:
      - TZ=Asia/Shanghai
    logging:
        driver: "json-file"
        options:
            max-size: "1m"
    network_mode: bridge
    ports:
      - "9191:80/tcp"
    volumes:
      - data:/data
    user: "${UID}:${GID}"
volumes:
  data:
