version: '3'

services:
  xiaoya-tvbox:
    image: haroldli/xiaoya-tvbox:latest
    container_name: xiaoya-tvbox
    restart: always
    platform: ${PLATFORM:-linux/amd64}  # 自动检测平台
    ports:
      - "${PORT1:-4567}:4567"  # 管理界面端口
      - "${PORT2:-5344}:80"    # AList端口
    environment:
      - ALIST_PORT=${PORT2:-5344}
    volumes:
      - ${BASE_DIR:-xiaoya_data}:/data
      # 如需添加额外挂载点，请取消下面的注释并修改路径
      # - /path/to/local:/path/in/container
    extra_hosts:
      - "access.mypikpak.com:127.0.0.1"

volumes:
  xiaoya_data: